/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/administracao/': RouteRecordInfo<'/administracao/', '/administracao', Record<never, never>, Record<never, never>>,
    '/administracao/clientes': RouteRecordInfo<'/administracao/clientes', '/administracao/clientes', Record<never, never>, Record<never, never>>,
    '/administracao/perfil': RouteRecordInfo<'/administracao/perfil', '/administracao/perfil', Record<never, never>, Record<never, never>>,
    '/administracao/sistemas': RouteRecordInfo<'/administracao/sistemas', '/administracao/sistemas', Record<never, never>, Record<never, never>>,
    '/administracao/usuarios': RouteRecordInfo<'/administracao/usuarios', '/administracao/usuarios', Record<never, never>, Record<never, never>>,
    '/dashboard01': RouteRecordInfo<'/dashboard01', '/dashboard01', Record<never, never>, Record<never, never>>,
    '/dashboard02': RouteRecordInfo<'/dashboard02', '/dashboard02', Record<never, never>, Record<never, never>>,
    '/dashboard03': RouteRecordInfo<'/dashboard03', '/dashboard03', Record<never, never>, Record<never, never>>,
    '/dashboard04': RouteRecordInfo<'/dashboard04', '/dashboard04', Record<never, never>, Record<never, never>>,
    '/dashboard05': RouteRecordInfo<'/dashboard05', '/dashboard05', Record<never, never>, Record<never, never>>,
    '/dashboard06': RouteRecordInfo<'/dashboard06', '/dashboard06', Record<never, never>, Record<never, never>>,
    '/dashboard07': RouteRecordInfo<'/dashboard07', '/dashboard07', Record<never, never>, Record<never, never>>,
    '/dashboard08': RouteRecordInfo<'/dashboard08', '/dashboard08', Record<never, never>, Record<never, never>>,
    '/financeiro': RouteRecordInfo<'/financeiro', '/financeiro', Record<never, never>, Record<never, never>>,
    '/financeiro02': RouteRecordInfo<'/financeiro02', '/financeiro02', Record<never, never>, Record<never, never>>,
    '/financeiro1': RouteRecordInfo<'/financeiro1', '/financeiro1', Record<never, never>, Record<never, never>>,
    '/financeiro2': RouteRecordInfo<'/financeiro2', '/financeiro2', Record<never, never>, Record<never, never>>,
    '/financeiro3': RouteRecordInfo<'/financeiro3', '/financeiro3', Record<never, never>, Record<never, never>>,
    '/generic-error': RouteRecordInfo<'/generic-error', '/generic-error', Record<never, never>, Record<never, never>>,
    '/lucratividade': RouteRecordInfo<'/lucratividade', '/lucratividade', Record<never, never>, Record<never, never>>,
    '/newpassword': RouteRecordInfo<'/newpassword', '/newpassword', Record<never, never>, Record<never, never>>,
    '/pagamentos': RouteRecordInfo<'/pagamentos', '/pagamentos', Record<never, never>, Record<never, never>>,
    '/perfil': RouteRecordInfo<'/perfil', '/perfil', Record<never, never>, Record<never, never>>,
    '/resultados': RouteRecordInfo<'/resultados', '/resultados', Record<never, never>, Record<never, never>>,
    '/ResumoContas': RouteRecordInfo<'/ResumoContas', '/ResumoContas', Record<never, never>, Record<never, never>>,
  }
}
